# Generated by Django 4.2.11 on 2024-03-08 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trash',
            old_name='age',
            new_name='peicesOfTrash',
        ),
    ]
